Improve error and debug messages

diff --git a/check_dnsserials b/check_dnsserials
--- a/check_dnsserials
+++ b/check_dnsserials
@@ -108,7 +108,7 @@ done
 [ -n "${COMMAND_DIG}" ] || error "No command 'dig' available."
 [ -n "${domain}" ]      || error "No domain specified!"
 
-verbose "domain ${domain}"
+verbose "Domain ${domain}"
 
 # check warning and critical values
 [ -z "${crit}" ] || [ "${crit}" -ge 0 ] \
@@ -120,30 +120,32 @@ verbose "domain ${domain}"
 
 # if no master given, use the standard DNS to determine the master
 if [ -z "${master}" ]; then
-	debug "getting master DNS from system"
+	debug "Getting master NS from DNS"
 	soa=($("${COMMAND_DIG}" +short SOA "${domain}" | cut -d " " -f 1,3))
 	master="${soa[0]}"
 fi
-verbose "Master DNS: ${master}"
+[ -n "${master}" ] || error "Cannot find a master NS for ${domain}"
+verbose "Master NS: ${master}"
 
 # if no serial given, get the master server to determine the serial
 if [ -z "${serial}" ]; then
-	debug "getting master serial from ${master}"
+	debug "Getting master serial from ${master}"
 	soa=($("${COMMAND_DIG}" +short SOA "@${master}" "${domain}" | cut -d " " -f 1,3))
 	serial="${soa[1]}"
 fi
+[ -n "${serial}" ] || error "Cannot grab a serial number from master ${master}"
 verbose "Master serial: ${serial}"
 
 # iterate the NS-RRs grabbed from master dns-server for the domain
 for server in $("${COMMAND_DIG}" +short NS "@${master}" "${domain}"); do
-	debug "getting slave serial from ${server}"
+	debug "Getting slave serial from ${server}"
 	serial_slave=$("${COMMAND_DIG}" +short SOA "@${server}" "${domain}" | cut -d " " -f 3)
 	if [ "x${serial_slave}" = "x${serial}" ]; then
-		verbose "ok: serial: ${serial} ${domain} ${server}"
+		verbose "OK:  ${domain} ${server} ${serial}"
 		else
 			verbose "BAD: ${domain} ${server} ${serial_slave}"
 			fails=$((fails + 1))
-			debug "incrementing failed states to ${fails}"
+			debug "Incrementing failed states to ${fails}"
 	fi
 done
 
