Use variables always like "${var}"

diff --git a/check_dnsserials b/check_dnsserials
--- a/check_dnsserials
+++ b/check_dnsserials
@@ -74,7 +74,7 @@ state="${STATE_UNKNOWN}"
 while getopts ":vhd:H:s:c:w:" opt; do
 	case "${opt}" in
 		v)
-			verbose=$(($verbose + 1))
+			verbose=$((verbose + 1))
 			;;
 		h)
 			usage
@@ -119,50 +119,50 @@ verbose "domain ${domain}"
 	|| error "Warning value has to be lower than critical."
 
 # if no master given, use the standard DNS to determine the master
-if [ -z "$master" ]; then
+if [ -z "${master}" ]; then
 	debug "getting master DNS from system"
-	soa=($($COMMAND_DIG +short SOA $domain | cut -d " " -f 1,3))
-	master=${soa[0]}
+	soa=($("${COMMAND_DIG}" +short SOA "${domain}" | cut -d " " -f 1,3))
+	master="${soa[0]}"
 fi
-verbose "Master DNS: $master"
+verbose "Master DNS: ${master}"
 
 # if no serial given, get the master server to determine the serial
-if [ -z "$serial" ]; then
-	debug "getting master serial from $master"
-	soa=($($COMMAND_DIG +short SOA @$master $domain | cut -d " " -f 1,3))
-	serial=${soa[1]}
+if [ -z "${serial}" ]; then
+	debug "getting master serial from ${master}"
+	soa=($("${COMMAND_DIG}" +short SOA "@${master}" "${domain}" | cut -d " " -f 1,3))
+	serial="${soa[1]}"
 fi
-verbose "Master serial: $serial"
+verbose "Master serial: ${serial}"
 
 # iterate the NS-RRs grabbed from master dns-server for the domain
-for server in $($COMMAND_DIG +short NS @$master $domain); do
-	debug "getting slave serial from $server"
-	serial_slave=$($COMMAND_DIG +short SOA @$server $domain | cut -d " " -f 3)
-	if [ "x$serial_slave" = "x$serial" ]; then
-		verbose "ok: serial: $serial $domain $server"
+for server in $("${COMMAND_DIG}" +short NS "@${master}" "${domain}"); do
+	debug "getting slave serial from ${server}"
+	serial_slave=$("${COMMAND_DIG}" +short SOA "@${server}" "${domain}" | cut -d " " -f 3)
+	if [ "x${serial_slave}" = "x${serial}" ]; then
+		verbose "ok: serial: ${serial} ${domain} ${server}"
 		else
-			verbose "BAD: $domain $server $serial_slave"
-			fails=$(($fails + 1))
-			debug "incrementing failed states to $fails"
+			verbose "BAD: ${domain} ${server} ${serial_slave}"
+			fails=$((fails + 1))
+			debug "incrementing failed states to ${fails}"
 	fi
 done
 
 # interpret the amount of fails
-if [[ -n "$warn" && $fails -gt $warn ]]; then
-	state=$STATE_WARN
-	msg="DNS WARN, master serial: $serial, fails: $fails"
+if [[ -n "${warn}" && "${fails}" -gt "${warn}" ]]; then
+	state="${STATE_WARN}"
+	msg="DNS WARN, master serial: ${serial}, fails: ${fails}"
 fi
-if [[ -n "$crit" && $fails -gt $crit ]]; then
-	state=$STATE_CRITICAL
-	msg="DNS CRITICAL, master serial: $serial, fails: $fails"
+if [[ -n "${crit}" && "${fails}" -gt "${crit}" ]]; then
+	state="${STATE_CRITICAL}"
+	msg="DNS CRITICAL, master serial: ${serial}, fails: ${fails}"
 fi
-if [[ -z "$crit" && -z "$warn" && $fails -gt 0 ]]; then
-	state=$STATE_CRITICAL
-	msg="DNS CRITICAL, master serial: $serial, fails: $fails"
+if [[ -z "${crit}" && -z "${warn}" && "${fails}" -gt 0 ]]; then
+	state="${STATE_CRITICAL}"
+	msg="DNS CRITICAL, master serial: ${serial}, fails: ${fails}"
 	else
-		msg="DNS OK, master serial: $serial, fails: $fails"
-		state=$STATE_OK
+		msg="DNS OK, master serial: ${serial}, fails: ${fails}"
+		state="${STATE_OK}"
 fi
 
-echo $msg
-exit $state
+echo "${msg}"
+exit "${state}"
